#ifndef _DATA_COLLECTION_ACCESS_TOKEN_REQ_H_
#define _DATA_COLLECTION_ACCESS_TOKEN_REQ_H_

/**********************************************************************************************************************************
 * AccessTokenReq - Public C interface to the AccessTokenReq object
 **********************************************************************************************************************************
 * License: 5G-MAG Public License (v1.0)
 * Authors: David Waring <david.waring2@bbc.co.uk>
 * Copyright: (C) 2024 British Broadcasting Corporation
 *
 * For full license terms please see the LICENSE file distributed with this
 * program. If this file is missing then the license can be retrieved from
 * https://drive.google.com/file/d/1cinCiA778IErENZ3JN52VFW-1ffHpx7Z/view
 **********************************************************************************************************************************/

#ifndef INCLUDED_FROM_DATA_COLLECTION_H
#error "This file can only be included from data-collection.h"
#endif

#include "NFType.h"
#include "PlmnIdNid.h"
#include "NwdafEvent.h"
#include "PlmnId.h"
#include "MlModelInterInd.h"
#include "Snssai.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct data_collection_model_access_token_req_s data_collection_model_access_token_req_t;

    
DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_create();

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_create_copy(const data_collection_model_access_token_req_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_create_move(data_collection_model_access_token_req_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_copy(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_access_token_req_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_move(data_collection_model_access_token_req_t *access_token_req, data_collection_model_access_token_req_t *other);

DATA_COLLECTION_SVC_PRODUCER_API void data_collection_model_access_token_req_free(data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API cJSON *data_collection_model_access_token_req_toJSON(const data_collection_model_access_token_req_t *access_token_req, bool as_request);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_fromJSON(cJSON *json, bool as_request, char **error_reason, char **error_class, char **error_parameter);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_grant_type(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_grant_type(data_collection_model_access_token_req_t *access_token_req, const char* p_grant_type);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_grant_type_move(data_collection_model_access_token_req_t *access_token_req, char* p_grant_type);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_nf_instance_id(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_nf_instance_id(data_collection_model_access_token_req_t *access_token_req, const char* p_nf_instance_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_nf_instance_id_move(data_collection_model_access_token_req_t *access_token_req, char* p_nf_instance_id);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_nf_type_t* data_collection_model_access_token_req_get_nf_type(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_nf_type(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_nf_type_t* p_nf_type);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_nf_type_move(data_collection_model_access_token_req_t *access_token_req, data_collection_model_nf_type_t* p_nf_type);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_nf_type_t* data_collection_model_access_token_req_get_target_nf_type(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_type(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_nf_type_t* p_target_nf_type);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_type_move(data_collection_model_access_token_req_t *access_token_req, data_collection_model_nf_type_t* p_target_nf_type);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_scope(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_scope(data_collection_model_access_token_req_t *access_token_req, const char* p_scope);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_scope_move(data_collection_model_access_token_req_t *access_token_req, char* p_scope);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_target_nf_instance_id(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_instance_id(data_collection_model_access_token_req_t *access_token_req, const char* p_target_nf_instance_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_instance_id_move(data_collection_model_access_token_req_t *access_token_req, char* p_target_nf_instance_id);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_plmn_id_t* data_collection_model_access_token_req_get_requester_plmn(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_plmn(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_plmn_id_t* p_requester_plmn);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_plmn_move(data_collection_model_access_token_req_t *access_token_req, data_collection_model_plmn_id_t* p_requester_plmn);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_access_token_req_get_requester_plmn_list(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_plmn_list(data_collection_model_access_token_req_t *access_token_req, const ogs_list_t* p_requester_plmn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_plmn_list_move(data_collection_model_access_token_req_t *access_token_req, ogs_list_t* p_requester_plmn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_add_requester_plmn_list(data_collection_model_access_token_req_t *access_token_req, data_collection_model_plmn_id_t* requester_plmn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_remove_requester_plmn_list(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_plmn_id_t* requester_plmn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_clear_requester_plmn_list(data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_access_token_req_get_requester_snssai_list(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_snssai_list(data_collection_model_access_token_req_t *access_token_req, const ogs_list_t* p_requester_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_snssai_list_move(data_collection_model_access_token_req_t *access_token_req, ogs_list_t* p_requester_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_add_requester_snssai_list(data_collection_model_access_token_req_t *access_token_req, data_collection_model_snssai_t* requester_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_remove_requester_snssai_list(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_snssai_t* requester_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_clear_requester_snssai_list(data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_requester_fqdn(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_fqdn(data_collection_model_access_token_req_t *access_token_req, const char* p_requester_fqdn);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_fqdn_move(data_collection_model_access_token_req_t *access_token_req, char* p_requester_fqdn);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_access_token_req_get_requester_snpn_list(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_snpn_list(data_collection_model_access_token_req_t *access_token_req, const ogs_list_t* p_requester_snpn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_snpn_list_move(data_collection_model_access_token_req_t *access_token_req, ogs_list_t* p_requester_snpn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_add_requester_snpn_list(data_collection_model_access_token_req_t *access_token_req, data_collection_model_plmn_id_nid_t* requester_snpn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_remove_requester_snpn_list(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_plmn_id_nid_t* requester_snpn_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_clear_requester_snpn_list(data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_plmn_id_t* data_collection_model_access_token_req_get_target_plmn(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_plmn(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_plmn_id_t* p_target_plmn);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_plmn_move(data_collection_model_access_token_req_t *access_token_req, data_collection_model_plmn_id_t* p_target_plmn);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_plmn_id_nid_t* data_collection_model_access_token_req_get_target_snpn(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_snpn(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_plmn_id_nid_t* p_target_snpn);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_snpn_move(data_collection_model_access_token_req_t *access_token_req, data_collection_model_plmn_id_nid_t* p_target_snpn);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_access_token_req_get_target_snssai_list(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_snssai_list(data_collection_model_access_token_req_t *access_token_req, const ogs_list_t* p_target_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_snssai_list_move(data_collection_model_access_token_req_t *access_token_req, ogs_list_t* p_target_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_add_target_snssai_list(data_collection_model_access_token_req_t *access_token_req, data_collection_model_snssai_t* target_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_remove_target_snssai_list(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_snssai_t* target_snssai_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_clear_target_snssai_list(data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_access_token_req_get_target_nsi_list(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nsi_list(data_collection_model_access_token_req_t *access_token_req, const ogs_list_t* p_target_nsi_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nsi_list_move(data_collection_model_access_token_req_t *access_token_req, ogs_list_t* p_target_nsi_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_add_target_nsi_list(data_collection_model_access_token_req_t *access_token_req, char* target_nsi_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_remove_target_nsi_list(data_collection_model_access_token_req_t *access_token_req, const char* target_nsi_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_clear_target_nsi_list(data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_target_nf_set_id(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_set_id(data_collection_model_access_token_req_t *access_token_req, const char* p_target_nf_set_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_set_id_move(data_collection_model_access_token_req_t *access_token_req, char* p_target_nf_set_id);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_target_nf_service_set_id(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_service_set_id(data_collection_model_access_token_req_t *access_token_req, const char* p_target_nf_service_set_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_target_nf_service_set_id_move(data_collection_model_access_token_req_t *access_token_req, char* p_target_nf_service_set_id);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_hnrf_access_token_uri(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_hnrf_access_token_uri(data_collection_model_access_token_req_t *access_token_req, const char* p_hnrf_access_token_uri);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_hnrf_access_token_uri_move(data_collection_model_access_token_req_t *access_token_req, char* p_hnrf_access_token_uri);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_source_nf_instance_id(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_source_nf_instance_id(data_collection_model_access_token_req_t *access_token_req, const char* p_source_nf_instance_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_source_nf_instance_id_move(data_collection_model_access_token_req_t *access_token_req, char* p_source_nf_instance_id);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_access_token_req_get_vendor_id(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_vendor_id(data_collection_model_access_token_req_t *access_token_req, const char* p_vendor_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_vendor_id_move(data_collection_model_access_token_req_t *access_token_req, char* p_vendor_id);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_access_token_req_get_analytics_ids(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_analytics_ids(data_collection_model_access_token_req_t *access_token_req, const ogs_list_t* p_analytics_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_analytics_ids_move(data_collection_model_access_token_req_t *access_token_req, ogs_list_t* p_analytics_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_add_analytics_ids(data_collection_model_access_token_req_t *access_token_req, data_collection_model_nwdaf_event_t* analytics_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_remove_analytics_ids(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_nwdaf_event_t* analytics_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_clear_analytics_ids(data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_access_token_req_get_requester_inter_ind_list(const data_collection_model_access_token_req_t *access_token_req);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_inter_ind_list(data_collection_model_access_token_req_t *access_token_req, const ogs_list_t* p_requester_inter_ind_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_set_requester_inter_ind_list_move(data_collection_model_access_token_req_t *access_token_req, ogs_list_t* p_requester_inter_ind_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_add_requester_inter_ind_list(data_collection_model_access_token_req_t *access_token_req, data_collection_model_ml_model_inter_ind_t* requester_inter_ind_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_remove_requester_inter_ind_list(data_collection_model_access_token_req_t *access_token_req, const data_collection_model_ml_model_inter_ind_t* requester_inter_ind_list);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_access_token_req_t *data_collection_model_access_token_req_clear_requester_inter_ind_list(data_collection_model_access_token_req_t *access_token_req);

/* lnode helper for generating ogs_list_t nodes's of type AccessTokenReq */
DATA_COLLECTION_SVC_PRODUCER_API data_collection_lnode_t *data_collection_model_access_token_req_make_lnode(data_collection_model_access_token_req_t *access_token_req);

/***** Internal library protected functions *****/

#ifdef __cplusplus
}
#endif

/* vim:ts=8:sts=4:sw=4:expandtab:
 */

#endif /* ifndef _DATA_COLLECTION_ACCESS_TOKEN_REQ_H_ */

