#ifndef _DATA_COLLECTION_CONSUMPTION_REPORTING_EVENT_H_
#define _DATA_COLLECTION_CONSUMPTION_REPORTING_EVENT_H_

/**********************************************************************************************************************************
 * ConsumptionReportingEvent - Public C interface to the ConsumptionReportingEvent object
 **********************************************************************************************************************************
 * License: 5G-MAG Public License (v1.0)
 * Authors: David Waring <david.waring2@bbc.co.uk>
 * Copyright: (C) 2024 British Broadcasting Corporation
 *
 * For full license terms please see the LICENSE file distributed with this
 * program. If this file is missing then the license can be retrieved from
 * https://drive.google.com/file/d/1cinCiA778IErENZ3JN52VFW-1ffHpx7Z/view
 **********************************************************************************************************************************/

#ifndef INCLUDED_FROM_DATA_COLLECTION_H
#error "This file can only be included from data-collection.h"
#endif

#include "EventRecordType.h"
#include "LocationArea5G.h"
#include "Snssai.h"
#include "EndpointAddress.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct data_collection_model_consumption_reporting_event_s data_collection_model_consumption_reporting_event_t;

    
DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_create();

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_create_copy(const data_collection_model_consumption_reporting_event_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_create_move(data_collection_model_consumption_reporting_event_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_copy(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const data_collection_model_consumption_reporting_event_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, data_collection_model_consumption_reporting_event_t *other);

DATA_COLLECTION_SVC_PRODUCER_API void data_collection_model_consumption_reporting_event_free(data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API cJSON *data_collection_model_consumption_reporting_event_toJSON(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event, bool as_request);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_fromJSON(cJSON *json, bool as_request, char **error_reason, char **error_class, char **error_parameter);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_is_equal_to(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const data_collection_model_consumption_reporting_event_t *other_consumption_reporting_event);



DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_event_record_type_t* data_collection_model_consumption_reporting_event_get_record_type(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_record_type(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const data_collection_model_event_record_type_t* p_record_type);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_record_type_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, data_collection_model_event_record_type_t* p_record_type);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_record_timestamp(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_record_timestamp(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_record_timestamp);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_record_timestamp_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_record_timestamp);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_app_id(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_app_id(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_app_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_app_id_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_app_id);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_provisioning_session_id(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_provisioning_session_id(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_provisioning_session_id(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_provisioning_session_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_provisioning_session_id_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_provisioning_session_id);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_session_id(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_session_id(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_session_id(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_session_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_session_id_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_session_id);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_ue_identification(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_ue_identification(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_ue_identification(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_ue_identification);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_ue_identification_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_ue_identification);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_data_network_name(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_data_network_name(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_data_network_name(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_data_network_name);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_data_network_name_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_data_network_name);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_slice_id(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_snssai_t* data_collection_model_consumption_reporting_event_get_slice_id(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_slice_id(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const data_collection_model_snssai_t* p_slice_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_slice_id_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, data_collection_model_snssai_t* p_slice_id);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_ue_locations(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_consumption_reporting_event_get_ue_locations(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_ue_locations(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const ogs_list_t* p_ue_locations);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_ue_locations_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, ogs_list_t* p_ue_locations);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_add_ue_locations(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, data_collection_model_location_area5_g_t* ue_locations);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_remove_ue_locations(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const data_collection_model_location_area5_g_t* ue_locations);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_location_area5_g_t* data_collection_model_consumption_reporting_event_get_entry_ue_locations(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event, size_t idx);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_clear_ue_locations(data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_unit_duration(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_unit_duration(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_unit_duration);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_unit_duration_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_unit_duration);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_client_endpoint_address(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_endpoint_address_t* data_collection_model_consumption_reporting_event_get_client_endpoint_address(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_client_endpoint_address(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const data_collection_model_endpoint_address_t* p_client_endpoint_address);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_client_endpoint_address_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, data_collection_model_endpoint_address_t* p_client_endpoint_address);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_consumption_reporting_event_has_server_endpoint_address(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);


DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_endpoint_address_t* data_collection_model_consumption_reporting_event_get_server_endpoint_address(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_server_endpoint_address(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const data_collection_model_endpoint_address_t* p_server_endpoint_address);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_server_endpoint_address_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, data_collection_model_endpoint_address_t* p_server_endpoint_address);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_media_player_entry_url(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_media_player_entry_url(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_media_player_entry_url);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_media_player_entry_url_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_media_player_entry_url);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_consumption_reporting_event_get_media_component_identifier(const data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_media_component_identifier(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, const char* p_media_component_identifier);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_consumption_reporting_event_t *data_collection_model_consumption_reporting_event_set_media_component_identifier_move(data_collection_model_consumption_reporting_event_t *consumption_reporting_event, char* p_media_component_identifier);

/* lnode helper for generating ogs_list_t nodes's of type ConsumptionReportingEvent */
DATA_COLLECTION_SVC_PRODUCER_API data_collection_lnode_t *data_collection_model_consumption_reporting_event_make_lnode(data_collection_model_consumption_reporting_event_t *consumption_reporting_event);

/***** Internal library protected functions *****/

#ifdef __cplusplus
}
#endif

/* vim:ts=8:sts=4:sw=4:expandtab:
 */

#endif /* ifndef _DATA_COLLECTION_CONSUMPTION_REPORTING_EVENT_H_ */

