#ifndef _DATA_COLLECTION_MEDIA_STREAMING_ACCESS_RECORD_H_
#define _DATA_COLLECTION_MEDIA_STREAMING_ACCESS_RECORD_H_

/**********************************************************************************************************************************
 * MediaStreamingAccessRecord - Public C interface to the MediaStreamingAccessRecord object
 **********************************************************************************************************************************
 * License: 5G-MAG Public License (v1.0)
 * Authors: David Waring <david.waring2@bbc.co.uk>
 * Copyright: (C) 2024 British Broadcasting Corporation
 *
 * For full license terms please see the LICENSE file distributed with this
 * program. If this file is missing then the license can be retrieved from
 * https://drive.google.com/file/d/1cinCiA778IErENZ3JN52VFW-1ffHpx7Z/view
 **********************************************************************************************************************************/

#ifndef INCLUDED_FROM_DATA_COLLECTION_H
#error "This file can only be included from data-collection.h"
#endif

#include "MediaStreamingAccess_requestMessage.h"
#include "TypedLocation.h"
#include "MediaStreamingAccess_connectionMetrics.h"
#include "MediaStreamingAccess_responseMessage.h"
#include "Snssai.h"
#include "EndpointAddress.h"
#include "CacheStatus.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct data_collection_model_media_streaming_access_record_s data_collection_model_media_streaming_access_record_t;

    
DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_create();

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_create_copy(const data_collection_model_media_streaming_access_record_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_create_move(data_collection_model_media_streaming_access_record_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_copy(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_media_streaming_access_record_t *other);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_media_streaming_access_record_t *other);

DATA_COLLECTION_SVC_PRODUCER_API void data_collection_model_media_streaming_access_record_free(data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API cJSON *data_collection_model_media_streaming_access_record_toJSON(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record, bool as_request);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_fromJSON(cJSON *json, bool as_request, char **error_reason, char **error_class, char **error_parameter);

DATA_COLLECTION_SVC_PRODUCER_API bool data_collection_model_media_streaming_access_record_is_equal_to(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_media_streaming_access_record_t *other_media_streaming_access_record);


DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_media_streaming_access_record_get_timestamp(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_timestamp(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const char* p_timestamp);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_timestamp_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, char* p_timestamp);

DATA_COLLECTION_SVC_PRODUCER_API ogs_list_t* data_collection_model_media_streaming_access_record_get_context_ids(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_context_ids(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const ogs_list_t* p_context_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_context_ids_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, ogs_list_t* p_context_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_add_context_ids(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, char* context_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_remove_context_ids(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const char* context_ids);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_clear_context_ids(data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_snssai_t* data_collection_model_media_streaming_access_record_get_slice_info(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_slice_info(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_snssai_t* p_slice_info);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_slice_info_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_snssai_t* p_slice_info);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_media_streaming_access_record_get_data_network_name(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_data_network_name(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const char* p_data_network_name);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_data_network_name_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, char* p_data_network_name);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_typed_location_t* data_collection_model_media_streaming_access_record_get_location(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_location(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_typed_location_t* p_location);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_location_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_typed_location_t* p_location);

DATA_COLLECTION_SVC_PRODUCER_API const char* data_collection_model_media_streaming_access_record_get_session_id(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_session_id(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const char* p_session_id);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_session_id_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, char* p_session_id);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_endpoint_address_t* data_collection_model_media_streaming_access_record_get_media_stream_handler_endpoint_address(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_media_stream_handler_endpoint_address(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_endpoint_address_t* p_media_stream_handler_endpoint_address);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_media_stream_handler_endpoint_address_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_endpoint_address_t* p_media_stream_handler_endpoint_address);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_endpoint_address_t* data_collection_model_media_streaming_access_record_get_application_server_endpoint_address(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_application_server_endpoint_address(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_endpoint_address_t* p_application_server_endpoint_address);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_application_server_endpoint_address_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_endpoint_address_t* p_application_server_endpoint_address);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_media_streaming_access_request_message_t* data_collection_model_media_streaming_access_record_get_request_message(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_request_message(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_media_streaming_access_request_message_t* p_request_message);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_request_message_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_media_streaming_access_request_message_t* p_request_message);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_cache_status_t* data_collection_model_media_streaming_access_record_get_cache_status(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_cache_status(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_cache_status_t* p_cache_status);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_cache_status_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_cache_status_t* p_cache_status);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_media_streaming_access_response_message_t* data_collection_model_media_streaming_access_record_get_response_message(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_response_message(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_media_streaming_access_response_message_t* p_response_message);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_response_message_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_media_streaming_access_response_message_t* p_response_message);

DATA_COLLECTION_SVC_PRODUCER_API const float data_collection_model_media_streaming_access_record_get_processing_latency(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_processing_latency(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const float p_processing_latency);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_processing_latency_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, float p_processing_latency);

DATA_COLLECTION_SVC_PRODUCER_API const data_collection_model_media_streaming_access_connection_metrics_t* data_collection_model_media_streaming_access_record_get_connection_metrics(const data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_connection_metrics(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, const data_collection_model_media_streaming_access_connection_metrics_t* p_connection_metrics);

DATA_COLLECTION_SVC_PRODUCER_API data_collection_model_media_streaming_access_record_t *data_collection_model_media_streaming_access_record_set_connection_metrics_move(data_collection_model_media_streaming_access_record_t *media_streaming_access_record, data_collection_model_media_streaming_access_connection_metrics_t* p_connection_metrics);

/* lnode helper for generating ogs_list_t nodes's of type MediaStreamingAccessRecord */
DATA_COLLECTION_SVC_PRODUCER_API data_collection_lnode_t *data_collection_model_media_streaming_access_record_make_lnode(data_collection_model_media_streaming_access_record_t *media_streaming_access_record);

/***** Internal library protected functions *****/

#ifdef __cplusplus
}
#endif

/* vim:ts=8:sts=4:sw=4:expandtab:
 */

#endif /* ifndef _DATA_COLLECTION_MEDIA_STREAMING_ACCESS_RECORD_H_ */

